name: Build
on:
  push:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make clean all

    - name: Print Version
      run: ./build/scumbago -version
